# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.define "lb1" do |lb1|
    lb1.vm.box = "chef/debian-7.4"

    lb1.vm.provision "shell", path: "install_lb.sh"

    lb1.vm.network "private_network", ip: "192.168.0.11"
  end

  config.vm.define "lb2" do |lb2|
    lb2.vm.box = "chef/debian-7.4"

    lb2.vm.provision "shell", path: "install_lb.sh"

    lb2.vm.network "private_network", ip: "192.168.0.12"
  end

  config.vm.define "ngx1" do |ngx1|
    ngx1.vm.box = "chef/debian-7.4"

    ngx1.vm.provision "shell", path: "install_nginx.sh"

    ngx1.vm.network "private_network", ip: "192.168.0.21", virtualbox__intnet: "privnet"
  end

  config.vm.define "ngx2" do |ngx2|
    ngx2.vm.box = "chef/debian-7.4"

    ngx2.vm.provision "shell", path: "install_nginx.sh"

    ngx2.vm.network "private_network", ip: "192.168.0.22", virtualbox__intnet: "privnet"
  end
end

